# Generated by Django 3.2 on 2022-11-11 21:38

from django.db import migrations, models
import patients.validators


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_alter_patient_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='national_code',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_code',
            field=models.CharField(max_length=10, null=True, validators=[patients.validators.national_code_validator]),
        ),
    ]
