# Generated by Django 3.2 on 2022-11-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_rename_cost_visit_doctoruser_cost_of_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='national_code',
        ),
    ]
